<?php

namespace AppBundle\Repository;

/**
 * croisiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class croisiereRepository extends \Doctrine\ORM\EntityRepository
{
}
